apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  strategy: {}
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - image: aakkiiff/jenkinstest:30
        name: project
